--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Farmero14000/PiggyCratesV2
build-by-default: true
branches:
- main
projects:
  PiggyCratesV2:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.2.0
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
        branch: “pm5”
      - src: DaPigGuy/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^1.0.0
    lint:
      phpstan: false
...
