keys:
  id: TRIPWIRE_HOOK
  enchantid: MENDING 
  enchantlevel: 1 # Value must be greater than 0!
  name: "{CRATE} Key"
  lore: "Claim rewards from a {CRATE} Crate"
crates:
  # Sound
  getsound: random.explode
  rollsound: random.orb
  # Options: instant, roulette
  mode: roulette
  roulette:
    # Minimum duration: (duration/speed) >= 5.5
    # If (duration/speed) ends up being less than 5.5, then your default time will be set to (6*speed)
    duration: 80
    # Minimum speed: speed >= 1
    # If speed ends up being less than 1, then your default speed will be set to 1.
    speed: 3
